// Substitua o conteúdo em: utils/wordlist.js
const wordlist = [
    "ABACAXI", "BALEIA", "CACHORRO", "DROMEDARIO", "ELEFANTE",
    "FUTEBOL", "GIRAFA", "HIPOPOTAMO", "IGREJA", "JACARE",
    "KIWI", "LARANJA", "MELANCIA", "NAVIO", "OCULOS",
    "PARALELEPIPEDO", "QUEIJO", "RELOGIO", "SAPATO", "TELEFONE",
    "UVA", "VIOLAO", "XICARA", "ZEBRA", "AMARELO",
    "BRINCADEIRA", "COMPUTADOR", "DESENVOLVEDOR", "ESCOLA", "FLORESTA",
    "GAVETA", "HOSPITAL", "JANELA", "LIVRO", "MOCHILA",
    "NUVEM", "ONIBUS", "PRAIA", "QUARTO", "RUA",
    "SERPENTE", "TARTARUGA", "UNIVERSO", "VENTILADOR", "WIFI",
    "YOUTUBE", "ZANGADO", "ALEGRIA", "BIBLIOTECA", "CAMINHAO",
    "DINOSSAURO", "ESTRELA", "FOGUETE", "GELADEIRA", "HELICOPTERO",
    "INTERNET", "JORNAL", "KARAOKE", "LABIRINTO", "MONTANHA",
    "NOTEBOOK", "ORQUESTRA", "PNEUMONIA", "QUADRADO", "RISADA",
    "SATELITE", "TERREMOTO", "UMIDADE", "VULCAO", "XADREZ",
    "YAKISOBA", "AERONAUTICA", "BIOGRAFIA", "CHOCOLATE", "DIAMANTE",
    "ELETRECIDADE", "FARMACIA", "GASTRONOMIA", "HARMONIA", "INDEPENDENCIA",
    "JURISPRUDENCIA", "KUNG FU", "LITERATURA", "MATEMATICA", "NEBULOSA",
    "OPORTUNIDADE", "PSICOLOGIA", "QUIMICA", "RESTAURANTE", "SINDICATO",
    "TECNOLOGIA", "URBANISMO", "VETERINARIO", "WEBINAR", "XENOFOBIA",
    "YOGA", "ZOOLOGICO", "AQUARELA", "BASQUETE", "CARNAVAL",
    "DOCUMENTARIO", "ECOLOGIA", "FANTASMA", "GEOGRAFIA", "HISTORIA",
    "INFORMATICA", "JARDINAGEM", "LEGISLACAO", "MICROFONE", "NATUREZA",
    "OCEANO", "PINTURA", "QUALIDADE", "RADIOGRAFIA", "SABONETE",
    "TRANSPORTE", "VANGUARDA", "XILOFONE", "ZODIACO", "AMBULANCIA",
    "BICICLETA", "CONSTITUICAO", "DICIONARIO", "ENGENHARIA", "FILOSOFIA",
    "GRAMATICA", "HORIZONTAL", "IDENTIDADE", "JOGATINA", "KARTODROMO",
    "LANTERNA", "METEOROLOGIA", "NEUROLOGIA", "ORTOPEDIA", "PEDIATRIA",
    "QUILOMETRO", "RESSONANCIA", "SINTAXE", "TERMOMETRO", "VERTICAL",
    "WORKSHOP", "ZEPPELIN", "ARQUITETURA", "BACTERIA", "COREOGRAFIA",
    "DEMOCRACIA", "EQUILIBRIO", "FOTOSSINTESE", "GLOBALIZACAO", "HIDROGENIO"
];

function getRandomWord() {
    return wordlist[Math.floor(Math.random() * wordlist.length)];
}

module.exports = { getRandomWord };